# Generated by Django 5.0 on 2026-03-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_location'),
        ('profiles', '0003_profile_email'),
    ]

    operations = [
    ]
