# Generated by Django 5.0 on 2026-02-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='current_school',
            field=models.BooleanField(default=False),
        ),
    ]
