# Generated by Django 5.0 on 2026-03-12 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_latitude_profile_location_profile_longitude'),
        ('profiles', '0004_merge_0002_profile_location_0003_profile_email'),
    ]

    operations = [
    ]
