# Generated by Django 5.0 on 2026-03-13 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_merge_20260312_1936'),
        ('profiles', '0005_profilesearch'),
    ]

    operations = [
    ]
