# Generated by Django 5.0 on 2026-02-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('employee', 'Employee')], default='employee', max_length=50),
        ),
    ]
