# Generated by Django 5.0 on 2026-02-10 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField(help_text="What is the job title?")),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                (
                    "skills",
                    models.TextField(
                        help_text="List all of your skills(E.g: Project Management, Agile Methodologies, etc.)"
                    ),
                ),
                ("salary_upper", models.IntegerField()),
                ("salary_lower", models.IntegerField()),
                (
                    "location",
                    models.TextField(
                        help_text="Where is this job listing located? Where do employees work from?"
                    ),
                ),
                (
                    "classification",
                    models.TextField(help_text="E.g: On-Site, Hybrid, Remote"),
                ),
                (
                    "isSponsoring",
                    models.BooleanField(
                        help_text="True: for OPT/CPT, F-1, J-1, etc., False: US citizens/Green Card holders"
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
