# Generated by Django 5.0 on 2026-02-17 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='What is the job title?', max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('skills', models.TextField(help_text='List all of your skills(E.g: Project Management, Agile Methodologies, etc.)')),
                ('salary_upper', models.IntegerField()),
                ('salary_lower', models.IntegerField()),
                ('location', models.CharField(help_text='Where is this job listing located? Where do employees work from?', max_length=255)),
                ('location_x', models.FloatField(help_text='X-Coordinate of office location')),
                ('location_y', models.FloatField(help_text='Y-Coordinate of office location')),
                ('classification', models.CharField(choices=[('On-Site', 'on-site'), ('Hybrid', 'hybrid'), ('Remote', 'remote')], max_length=20)),
                ('isSponsoring', models.BooleanField(help_text='True: for OPT/CPT, F-1, J-1, etc., False: US citizens/Green Card holders')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AP', 'Applied'), ('RE', 'Review'), ('IN', 'Interview'), ('OF', 'Offer'), ('CL', 'Closed')], default='AP', max_length=2)),
                ('note', models.CharField(blank=True, max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='single_application_per_user', violation_error_message='User has already applied to this job.'),
        ),
    ]
