# Generated by Django 5.0 on 2026-02-12 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="classification",
            field=models.CharField(
                help_text="E.g: On-Site, Hybrid, Remote", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="end_date",
            field=models.DateTimeField(blank="true", null="true"),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(
                help_text="Where is this job listing located? Where do employees work from?",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.CharField(
                help_text="List all of your skills(E.g: Project Management, Agile Methodologies, etc.)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="start_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(help_text="What is the job title?", max_length=255),
        ),
    ]
