# Generated by Django 5.0 on 2026-03-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='classification',
            field=models.CharField(help_text='E.g: On-Site, Hybrid, Remote', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(blank='true', null='true'),
        ),
    ]
