<<<<<<< HEAD
# Generated by Django 5.0 on 2026-03-10 16:56
=======
# Generated by Django 5.0 on 2026-03-12 14:47
>>>>>>> 22e9862b37862d968b4da87c474e1258c96b0035

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='classification',
<<<<<<< HEAD
            field=models.CharField(help_text='E.g: On-Site, Hybrid, Remote', max_length=255),
=======
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-Site')], help_text='E.g: On-Site, Hybrid, Remote', max_length=255),
>>>>>>> 22e9862b37862d968b4da87c474e1258c96b0035
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(blank='true', null='true'),
        ),
    ]
