# Generated by Django 5.0 on 2026-03-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_classification_alter_job_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location_x',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location_y',
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(help_text='Work location. Can accept address, city/state, etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(help_text='Required skills(E.g: Project Management, Agile Methodologies, etc.)'),
        ),
    ]
