# Generated by Django 5.0 on 2026-02-17 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_created_at_alter_job_classification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location_x',
            field=models.IntegerField(default=0, help_text='X-Coordinate of office location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='location_y',
            field=models.IntegerField(default=0, help_text='Y-Coordinate of office location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(help_text='List all of your skills(E.g: Project Management, Agile Methodologies, etc.)'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AP', 'Applied'), ('RE', 'Review'), ('IN', 'Interview'), ('OF', 'Offer'), ('CL', 'Closed')], default='AP', max_length=2)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='single_application_per_user', violation_error_message='User has already applied to this job.'),
        ),
    ]
