# Generated by Django 5.0 on 2026-03-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_location_x_remove_job_location_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='classification',
            field=models.CharField(choices=[('Remote', 'remote'), ('Hybrid', 'hybrid'), ('On-Site', 'on-site')], help_text='E.g: On-Site, Hybrid, Remote', max_length=255),
        ),
    ]
