# Generated by Django 5.0 on 2026-02-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_location_x_job_location_y_alter_job_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location_x',
            field=models.FloatField(help_text='X-Coordinate of office location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location_y',
            field=models.FloatField(help_text='Y-Coordinate of office location'),
        ),
    ]
