# Generated by Django 5.0 on 2026-03-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_remove_message_conversation_remove_message_publisher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_time',
            new_name='sent',
        ),
    ]
